In [8]:
%load_ext autoreload
%autoreload 2

In [9]:
import polars as pl

from utils import DATADIR, load_data_per_event

In [16]:
load_data_per_event(DATADIR / "1994" / "1.txt")

shape: (3_542, 11)
┌──────────┬──────────┬─────────┬────────┬───┬─────────┬───────┬───────┬───────┐
│ t1       ┆ t2       ┆ G1      ┆ G2     ┆ … ┆ G3bgsub ┆ eG1   ┆ eG2   ┆ eG3   │
│ ---      ┆ ---      ┆ ---     ┆ ---    ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---   │
│ f64      ┆ f64      ┆ f64     ┆ f64    ┆   ┆ f64     ┆ f64   ┆ f64   ┆ f64   │
╞══════════╪══════════╪═════════╪════════╪═══╪═════════╪═══════╪═══════╪═══════╡
│ -999.442 ┆ -997.97  ┆ 1166.85 ┆ 601.69 ┆ … ┆ 5.43    ┆ 28.16 ┆ 20.22 ┆ 12.7  │
│ -997.97  ┆ -996.498 ┆ 1141.9  ┆ 607.06 ┆ … ┆ -2.81   ┆ 27.85 ┆ 20.31 ┆ 12.48 │
│ -996.498 ┆ -995.026 ┆ 1163.44 ┆ 637.95 ┆ … ┆ -1.42   ┆ 28.11 ┆ 20.82 ┆ 12.52 │
│ -995.026 ┆ -993.554 ┆ 1117.18 ┆ 616.67 ┆ … ┆ 4.02    ┆ 27.55 ┆ 20.47 ┆ 12.66 │
│ -993.554 ┆ -992.082 ┆ 1128.35 ┆ 620.82 ┆ … ┆ 2.68    ┆ 27.69 ┆ 20.54 ┆ 12.63 │
│ …        ┆ …        ┆ …       ┆ …      ┆ … ┆ …       ┆ …     ┆ …     ┆ …     │
│ 241.454  ┆ 242.926  ┆ 1325.31 ┆ 648.23 ┆ … ┆ -8.93   ┆ 30.01 ┆ 20.98 ┆ 12.31 │
│ 242.926  ┆ 244.398  ┆ 1376.09 ┆ 618.7  ┆ … ┆ 9.47    ┆ 30.57 ┆ 20.5  ┆ 12.81 │
│ 244.398  ┆ 245.87   ┆ 1303.96 ┆ 629.82 ┆ … ┆ 12.94   ┆ 29.76 ┆ 20.68 ┆ 12.9  │
│ 245.87   ┆ 247.342  ┆ 1358.14 ┆ 637.9  ┆ … ┆ -15.78  ┆ 30.38 ┆ 20.82 ┆ 12.12 │
│ 247.342  ┆ 248.814  ┆ 1332.09 ┆ 633.13 ┆ … ┆ 19.73   ┆ 30.08 ┆ 20.74 ┆ 13.08 │
└──────────┴──────────┴─────────┴────────┴───┴─────────┴───────┴───────┴───────┘

In [12]:
pl.read_csv(DATADIR / "solar_events_metadata.csv").drop("href")

shape: (33, 6)
┌───────────┬─────┬─────┬─────┬─────┬───────┐
│ year      ┆ b   ┆ c   ┆ m   ┆ x   ┆ total │
│ ---       ┆ --- ┆ --- ┆ --- ┆ --- ┆ ---   │
│ str       ┆ i64 ┆ i64 ┆ i64 ┆ i64 ┆ i64   │
╞═══════════╪═════╪═════╪═════╪═════╪═══════╡
│ 1994*     ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1     │
│ 1995      ┆ 1   ┆ 2   ┆ 6   ┆ 0   ┆ 9     │
│ 1996      ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 2     │
│ 1997      ┆ 0   ┆ 6   ┆ 8   ┆ 3   ┆ 17    │
│ 1998      ┆ 1   ┆ 26  ┆ 25  ┆ 10  ┆ 62    │
│ …         ┆ …   ┆ …   ┆ …   ┆ …   ┆ …     │
│ 2022      ┆ 0   ┆ 7   ┆ 22  ┆ 5   ┆ 34    │
│ 2023      ┆ 0   ┆ 7   ┆ 23  ┆ 8   ┆ 38    │
│ 2024      ┆ 0   ┆ 9   ┆ 76  ┆ 30  ┆ 115   │
│ 2025      ┆ 0   ┆ 3   ┆ 13  ┆ 5   ┆ 21    │
│ All years ┆ 5   ┆ 337 ┆ 658 ┆ 180 ┆ 1180  │
└───────────┴─────┴─────┴─────┴─────┴───────┘